// This file is auto-generated by @nudge-ai/cli. Do not edit manually.
import { registerPrompts } from "@nudge-ai/core";

declare module "@nudge-ai/core" {
  interface PromptRegistry {

  }
}

const prompts = {

} as const;

registerPrompts(prompts);
